items/urls.py
from django.urls import path
from .views import (index, test_perm,
                    ItemUpdateView,
                    item_list,
                    item_detail_view,
                    expiring_list,
                    get_items,
                    delete_item,
                    search,
                    low_stock,
                    CategoryUpdateView,
                    CategoryCreateView,
                    delete_category,
                    category_detail,
                    cat_list,
                    item_page,
                    post_item,
                    add_to_shelf,
                    shelf_list, shelf_detail, update_shelf, delete_shelf, upload_excel


                    )

app_name = 'items'

urlpatterns = [

    path('add', test_perm, name='add'),
    path('add-item', item_page, name='add-item'),
    path('post-item', post_item, name="post-item"),
    path('upload-items', upload_excel, name="upload_items"),
    path("shelf/add-to-shelf", add_to_shelf, name="add_shelf"),
    path("shelf/list", shelf_list, name="shelf_list"),
    path("shelf/<int:pk>/detail", shelf_detail, name="shelf_detail"),
    path("shelf/<int:pk>/update", update_shelf, name="shelf_update"),
    path("shelf/<int:pk>/delete", delete_shelf, name="shelf_delete"),








    path('update/<int:pk>', ItemUpdateView.as_view(), name="item_update"),
    path('list', item_list, name='item_list'),
    path('expiring-list', expiring_list, name='expiring_list'),
    path('low-stock', low_stock, name='low_stock'),


    path("detail/<int:pk>/description", item_detail_view, name="item_detail"),
    path('<int:pk>/delete', delete_item, name='item_delete'),
    path("data", get_items, name="get-data"),
    path("search", search, name="search"),
    path("category/<int:pk>/update",
         CategoryUpdateView.as_view(), name="update_category"),
    path("category/create", CategoryCreateView.as_view(), name="category_create"),
    path("category/<int:pk>/delete", delete_category, name="category_delete"),
    path("category/list", cat_list, name="category_list"),
    path("category/<int:pk>/detail", category_detail, name="category_detail"),
    # path('item-update/<int:pk>', items_update, name="update"),



]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import ManagerSignUpView, user_list, UserCreateView, UserUpdateView, user_detail_view, user_update_view
from items.views import index, category_upload
from .views import ItemChart, chartview, settings_view, settings_update_view,upload_items
from carts.views import cart_home
from ajax_select import urls as ajax_select_urls

admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload-items',upload_items,name='upload-items'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/manager/',
         ManagerSignUpView.as_view(), name='manager_signup'),
    path('accounts/add/user/',
         UserCreateView.as_view(), name='add_user'),
    path('accounts/<int:pk>/update/user/',
         user_update_view, name='update_user'),
    path('accounts/<int:pk>/details/user/',
         user_detail_view, name='user_detail'),
    path('ajax_select/', include(ajax_select_urls)),



    path("accounts/users", user_list, name="users"),
    path("", index, name="index"),
    path("items/", include('items.urls')),
    path("orders/", include('orders.urls')),
    path("departments/", include("departments.urls")),
    path("api/chart/data/", ItemChart.as_view(), name="api-data"),
    path("chart/", chartview, name="chart"),
    path("cart", cart_home, name="cart"),
    path("upload", category_upload, name="upload"),
    path('settings', settings_view, name="settings"),
    # path('create-item', settings_view, name="create_item"),

    path('settings/<int:pk>/update', settings_update_view, name="settings_update"),







]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/category/category_details.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Category | Detail
{% endblock title %}




{% block content %}
<div class="page-inner no-page-title">
    <div id="main-wrapper">
        <div class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-style-1">
                    <li class="breadcrumb-item"><a href="{% url 'items:category_list' %}">Category</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Detail</li>
                </ol>
            </nav>
            <h1 class="page-title"></h1>
        </div>
        {% include 'snippets/messages.html' %}




        <div class="row">
            <div class="col-xl">
                <div class="card">
                    <div class="card-body">
                        <h4 class=" text-center">{{cat.name|title}}</h4>
                        <hr>

                        <button type="button" class="btn btn-primary" data-toggle="modal"
                            data-target=".bd-example-modal-lg">Update Category</button>
                        <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"
                            aria-labelledby="myLargeModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalCenterTitle">Update Category</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        {% include 'category/category_update.html' with  cat=cat form=form %}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Close</button>

                                    </div>
                                </div>
                            </div>
                        </div>


                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                            Delete {{cat.name|title}}
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">{{cat.name|title}}</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Are You Sure You Want To Delete <b>{{cat.name}} ? </b> All items
                                        Associated With This Category Will Be Deleted
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Close</button>
                                        <a href="{{cat.get_delete_url}}" class="btn btn-danger">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-xl">
                <div class="card">
                    <div class="card-body">
                        <div class="text text-center">
                            <h5 class="card-title">Associated Items</h5>
                        </div>






                        <hr>
                        <table class="table table-hover" id="table_id">
                            <thead>
                                <tr>

                                    <th scope="col">Item Name </th>
                                    <th scope="col">Item Quantity</th>
                                    <th scope="col">Expiry Date</th>
                                    <th scope="col">Actions</th>



                                </tr>
                            </thead>
                            <tbody>
                                {% for cats in cat.categories.all  %}
                                <tr>



                                    <td><a href="{{cats.get_absolute_url}}">{{cats.name}}</a></td>
                                    <td><a href="{{cats.get_absolute_url}}">{{cats.stock_on_hand}}</a></td>
                                    <td><a href="{{cats.get_absolute_url}}">{{cats.expiry_date}}</a></td>
                                    <td><a href="{{cats.get_absolute_url}}" class="btn btn-primary">View</a> </td>





                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>






    </div>
</div><!-- Main Wrapper -->
{% endblock content %}

templates/category/category_form.html
{% load crispy_forms_tags %}


<form action="{% url 'items:category_create' %}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{form|crispy}}
    </div>





    <div class="form-group">
        <input type="submit" value="Add Category" class="btn btn-info">
    </div>

</form>

templates/category/category_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Category | List
{% endblock title %}




{% block content %}
<!-- Page Inner -->
<div class="page-inner no-page-title">
    <div id="main-wrapper">
        <div class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-style-1">
                    <li class="breadcrumb-item"><a href="#">Category</a></li>

                </ol>
            </nav>
            {% include 'snippets/messages.html'  %}






            <div class="row">
                <div class="col-xl">
                    <div class="card">
                        <div class="card-body">
                            <div class="text text-center">
                                <h5 class="card-title">Category</h5>
                            </div>
                            <hr>
                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                data-target=".bd-example-modal-lg">Add New Category</button>
                            <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"
                                aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Add New Category</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            {% include 'category/category_form.html' with form=form %}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-dismiss="modal">Close</button>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <table class="table table-hover" id="table_id">
                                <thead>
                                    <tr>

                                        <th scope="col">Name </th>

                                        <th scope="col">Action </th>




                                    </tr>
                                </thead>
                                <tbody>
                                    {% for  cat in cats  %}
                                    <tr>



                                        <td>
                                            <a href="{{cat.get_absolute_url}}">{{cat.name}}</a></td>

                                        <td> <a href="{{cat.get_absolute_url}}" class="btn btn-info">View</a></td>





                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>





        </div>

    </div><!-- Main Wrapper -->
    {% endblock content %}


    <!-- {% block javascript %}
    <link rel="stylesheet" type="text/css"
        href="https://cdn.datatables.net/v/bs4/jq-3.3.1/jszip-2.5.0/dt-1.10.20/af-2.3.4/b-1.6.1/b-colvis-1.6.1/b-html5-1.6.1/kt-2.5.1/r-2.2.3/rg-1.1.1/sc-2.0.1/sl-1.3.1/datatables.min.css" />

    <script type="text/javascript"
        src="https://cdn.datatables.net/v/bs4/jq-3.3.1/jszip-2.5.0/dt-1.10.20/af-2.3.4/b-1.6.1/b-colvis-1.6.1/b-html5-1.6.1/kt-2.5.1/r-2.2.3/rg-1.1.1/sc-2.0.1/sl-1.3.1/datatables.min.js"></script>


    
    {% endblock javascript %} -->

templates/category/category_update.html
{% load crispy_forms_tags %}


<form action="{{cat.get_absolute_url}}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{form|crispy}}
    </div>





    <div class="form-group">
        <input type="submit" value="Add Category" class="btn btn-info">
    </div>

</form>