items/urls.py
from django.urls import path
from .views import (index, test_perm,
                    ItemUpdateView,
                    item_list,
                    item_detail_view,
                    expiring_list,
                    get_items,
                    delete_item,
                    search,
                    low_stock,
                    CategoryUpdateView,
                    CategoryCreateView,
                    delete_category,
                    category_detail,
                    cat_list,
                    item_page,
                    post_item,
                    add_to_shelf,
                    shelf_list, shelf_detail, update_shelf, delete_shelf, upload_excel


                    )

app_name = 'items'

urlpatterns = [

    path('add', test_perm, name='add'),
    path('add-item', item_page, name='add-item'),
    path('post-item', post_item, name="post-item"),
    path('upload-items', upload_excel, name="upload_items"),
    path("shelf/add-to-shelf", add_to_shelf, name="add_shelf"),
    path("shelf/list", shelf_list, name="shelf_list"),
    path("shelf/<int:pk>/detail", shelf_detail, name="shelf_detail"),
    path("shelf/<int:pk>/update", update_shelf, name="shelf_update"),
    path("shelf/<int:pk>/delete", delete_shelf, name="shelf_delete"),








    path('update/<int:pk>', ItemUpdateView.as_view(), name="item_update"),
    path('list', item_list, name='item_list'),
    path('expiring-list', expiring_list, name='expiring_list'),
    path('low-stock', low_stock, name='low_stock'),


    path("detail/<int:pk>/description", item_detail_view, name="item_detail"),
    path('<int:pk>/delete', delete_item, name='item_delete'),
    path("data", get_items, name="get-data"),
    path("search", search, name="search"),
    path("category/<int:pk>/update",
         CategoryUpdateView.as_view(), name="update_category"),
    path("category/create", CategoryCreateView.as_view(), name="category_create"),
    path("category/<int:pk>/delete", delete_category, name="category_delete"),
    path("category/list", cat_list, name="category_list"),
    path("category/<int:pk>/detail", category_detail, name="category_detail"),
    # path('item-update/<int:pk>', items_update, name="update"),



]

orders/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import (OrderCreateView,
                    OrderListView,
                    order_list_view,
                    order_detail_view,
                    order_update_view,
                    delete_view,
                    search,
                    create_order,
                    list_order,
                    order_update,
                    order_delete
                    )


app_name = 'orders'

urlpatterns = [
    path("new-order", OrderCreateView.as_view(), name="new_order"),
    path("order-list", order_list_view, name="list_order"),
    path("<int:pk>/order-detail", order_detail_view, name="order_detail"),
    path("<int:pk>/order-update", order_update_view, name="order_update"),
    path("<int:pk>/order-delete", delete_view, name="order_delete"),
    path("search", search, name="search"),
    path("list",list_order,name="list_order"),
    path("create",create_order,name="create_order"),
    path('<int:pk>/update', order_update, name='order_updates'),
    path('<int:pk>/delete', order_delete, name='delete_order'),

    


    
]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import ManagerSignUpView, user_list, UserCreateView, UserUpdateView, user_detail_view, user_update_view
from items.views import index, category_upload
from .views import ItemChart, chartview, settings_view, settings_update_view,upload_items
from carts.views import cart_home
from ajax_select import urls as ajax_select_urls

admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload-items',upload_items,name='upload-items'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/manager/',
         ManagerSignUpView.as_view(), name='manager_signup'),
    path('accounts/add/user/',
         UserCreateView.as_view(), name='add_user'),
    path('accounts/<int:pk>/update/user/',
         user_update_view, name='update_user'),
    path('accounts/<int:pk>/details/user/',
         user_detail_view, name='user_detail'),
    path('ajax_select/', include(ajax_select_urls)),



    path("accounts/users", user_list, name="users"),
    path("", index, name="index"),
    path("items/", include('items.urls')),
    path("orders/", include('orders.urls')),
    path("departments/", include("departments.urls")),
    path("api/chart/data/", ItemChart.as_view(), name="api-data"),
    path("chart/", chartview, name="chart"),
    path("cart", cart_home, name="cart"),
    path("upload", category_upload, name="upload"),
    path('settings', settings_view, name="settings"),
    # path('create-item', settings_view, name="create_item"),

    path('settings/<int:pk>/update', settings_update_view, name="settings_update"),







]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from items.models import Item, Category, User
from django.shortcuts import reverse
from departments.models import Department
# Create your models here.
from django.shortcuts import reverse


class Order(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    item = models.ForeignKey(
        Item, related_name="order_set", on_delete=models.CASCADE)
    date_of_order = models.DateField(auto_now=False)
    order_id = models.CharField(unique=True, max_length=50)
    quantity = models.IntegerField(default=1)

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)

    """Model definition for Order."""

    # TODO: Define fields here

    class Meta:

        """Meta definition for Order."""

        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        """Unicode representation of Order."""
        return self.item.name

    # def save(self):
    #     """Save method for Order."""
    #     pass
    # GET THE ORDER DETAIL URL
    def get_absolute_url(self):

        return reverse('orders:order_detail', kwargs={'pk': self.pk})

    # GET THE UPDATEBURL
    def get_update_url(self):

        return reverse('orders:order_update', kwargs={'pk': self.pk})

    # GET THE DELETE URL
    def get_delete_url(self):

        return reverse('orders:order_delete', kwargs={'pk': self.pk})

    # TODO: Define custom methods here

orders/forms.py
from django import forms
from items.models import Item
from departments.models import Department
from ajax_select.fields import AutoCompleteSelectMultipleField
from ajax_select.fields import AutoCompleteSelectField, AutoCompleteSelectMultipleField


from .models import Order
choice = Department.objects.all()


class DateInput(forms.DateInput):
    input_type = 'date'


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        widgets = {'date_of_order': DateInput()}
        fields = ("department", "shelf", "date_of_order", "quantity")

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView,View
# Create your views here.
from .models import Order
from .forms import OrderForm
from items.models import Item,ShelfItem
from departments.models import Department
from django.contrib import messages
from invoices.models import Invoice
import uuid
from .filters import OrderFilter
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.forms.models import model_to_dict

class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    template_name = "orders/new_order.html"

    def form_valid(self, form):

        shelf = ShelfItem.objects.get(item__name=form.instance.shelf)
        shelf.quantity = shelf.quantity-form.instance.quantity

        if shelf.quantity < form.instance.quantity:

            messages.success(
                    self.request, 'Order cannot be placed, requested items are more than the items in your inventory. Maximum quantity-{} that can be requested'.format(shelf.quantity))
            return redirect('orders:list_order')

        elif shelf.quantity < 1:
            messages.success(self.request, 'Item is low on stock')
            return redirect('orders:list_order')

        else:
            order_id = generate_random_string(shelf.item.name)
            form.instance.order_id = order_id
            shelf.save()
            form.instance.user=self.request.user
            form.save()
            order = get_order(order_id=order_id)
            invoice_id = invoice_id = generate_invoice_id()
            create_invoice(order, invoice_id)
            messages.success(
                self.request, 'Order Has Been Made')
            return redirect("orders:list_order")


class OrderListView(ListView):
    model = Order
    template_name = "orders/order_list.html"


def order_list_view(request):
    form = OrderForm()
    orders = Order.objects.all()
    items = Item.objects.all()
    departments = Department.objects.all()

    context = {
        'items': items,
        'departments': departments,
        'orders': orders,
        'form': form
    }

    return render(request, 'orders/order_list.html', context)


def generate_random_string(item):
    item_name = item.replace(' ', '-')
    rand_code = my_uuid = uuid.uuid4()
    return "{}-{}".format(item_name, rand_code)


# display the details of the order
def order_detail_view(request, pk):
    order = get_object_or_404(Order, pk=pk)
    form = OrderForm(request.POST or None, instance=order)

    context = {
        'order': order,
        'form': form
    }

    return render(request, 'orders/order_detail.html', context)


def order_update_view(request, pk):
    order = get_object_or_404(Order, pk=pk)
    new_order = get_order(order.order_id)
    # print(new_order.quantity)

    form = OrderForm(request.POST or None, instance=order)

    if request.method == "POST":

        form = OrderForm(request.POST or None, instance=order)

        if form.is_valid():
            shelf = ShelfItem.objects.get(item__name=form.instance.shelf)

            if shelf.quantity < form.instance.quantity:

                messages.success(
                    request, 'Order cannot be placed, requested items are more than the items in your inventory. Maximum quantity-{} that can be requested'.format(shelf.quantity))
                return redirect('orders:list_order')

            elif shelf.quantity < 1:
                messages.success(request, 'Item is low on stock')
                return redirect('orders:list_order')

            else:
                old_order = get_order(order.order_id)

                if form.instance.quantity < old_order.quantity:
                    newq = old_order.quantity-form.instance.quantity
                    print('item stock on hand : {}'.format(shelf.quantity))
                    shelf.quantity = shelf.quantity + newq
                    # print('item stock on hand : {}'.format(shelf.quantity))

                    shelf.save()
                    form.save()
                    # print('ew q : {}'.format(newq))

                    messages.success(request, 'Order Has Been Updated')
                    return redirect("orders:list_order")

                else:
                    new_order = get_order(order.order_id)

                    print("new quantity :{}".format(new_order.quantity))

                    newq = form.instance.quantity-old_order.quantity
                    shelf.quantity = shelf.quantity - newq
                    shelf.save()
                    form.save()

                    messages.success(request, "Order has Been Updated")

                    return redirect("orders:list_order")
                    # return redirect("orders:list_order")

    context = {
        'form': form,

    }

    return render(request, 'orders/order_update.html', context)


def stock():
    if itemstock-newquantity < 1:
        return True
    else:
        return False


def quantity(formquantity, quantity):
    if formquantity > quantity:
        return True
    else:
        return False


def get_order(order_id):
    try:
        qs = Order.objects.filter(order_id=order_id)
        return qs[0]

    except:
        return None


def delete_view(request, pk):
    order = get_object_or_404(Order, pk=pk)

    if request.method == "POST":

        order.delete()
        messages.success(request, "Item Has Been Deleted")
        return redirect('orders:list_order')


def generate_invoice_id():

    inv_code = my_uuid = uuid.uuid4()
    return "INV-{}".format(inv_code)


def create_invoice(order, invoice_id):
    inv = Invoice.objects.create(order=order, invoice_id=invoice_id)

    return inv


def search(request):
    orders = Order.objects.all()
    order_filter = OrderFilter(request.GET, queryset=orders)

    context = {
        'filter': order_filter
    }

    return render(request, 'orders/search.html', context)




def create_order(request):
    data=dict()
    orders=Order.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            item = Item.objects.get(name=form.instance.item)
            order_id = generate_random_string(item.name)
            form.instance.order_id = order_id
            form.save()
            data['form_is_valid'] = True
            data['html_order_list'] = render_to_string('orders/mylist.html', {
                'orders': orders
            })
        else:
            data['form_is_valid'] = False
    else:
        form = OrderForm()
    
    context={
        'form':form,
        'orders':orders
    }
    data['html_form']=render_to_string('snippets/order_create.html',context,request=request)

    return JsonResponse(data)


#     form=OrderForm()





#     context={'form':form}
#     html_form=render_to_string('snippets/order_create.html',context,request=request)
#     return JsonResponse({'html_form':html_form})

def list_order(request):
    order=Order.objects.all()
    context={
        'orders':order
    }

    return render(request,'orders/list.html',context)



def save_order_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            orders = Order.objects.all()
            data['html_order_list'] = render_to_string('orders/mylist.html', {
                'orders': orders
            #     messages.success(request, "success")
            # return redirect('orders:list')
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)



def order_update(request, pk):
    order = get_object_or_404(Order, pk=pk)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
    else:
        form = OrderForm(instance=order)
    return save_order_form(request, form, 'snippets/myupdate.html')


def order_delete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    data = dict()
    if request.method == 'POST':
        order.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        orders = Order.objects.all()
        data['html_order_list'] = render_to_string('orders/mylist.html', {'orders': orders})
    else:
        context = {'order': order}
        data['html_form'] = render_to_string('snippets/delete_order.html',
            context,
            request=request,
        )
    return JsonResponse(data)

templates/orders/form_order.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Create a new Order</h4>
    </div>
    <div class="modal-body">
        {{ form.media }}
        {{form|crispy}}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create Order</button>
    </div>
</form>

templates/orders/list.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<!-- Page Inner -->
<div class="page-inner no-page-title">
    <div id="main-wrapper">
        <div class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-style-1">
                    <li class="breadcrumb-item"><a href="{% url 'orders:list_order' %}">Orders</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Order List</li>
                </ol>
            </nav>



            {% include 'snippets/messages.html' %}
            <div class="message" id="messages"></div>

            <div class="row">
                <div class="col-xl">
                    <div class="card">
                        <div class="card-body">
                            <div class="text text-center">
                                <h5 class="card-title">Orders</h5>
                            </div>
                            <button type="button" class="btn btn-primary js-create-book"
                                data-url="{% url 'orders:create_order' %}">
                                <span class="glyphicon glyphicon-plus"></span>
                                New Order
                            </button>
                            <hr>





                            {% include 'orders/mylist.html' with orders=orders %}



                            <div class="modal fade" id="modal-book">
                                <div class="modal-dialog">
                                    <div class="modal-content">


                                    </div>
                                </div>

                            </div>


                        </div>
                    </div>
                </div>
            </div>





        </div>

    </div><!-- Main Wrapper -->


    {% endblock content %}



    {% block extrajs %}
    <script src="{% static './assets/js/app.js' %}"></script>
    {% endblock extrajs %}

templates/orders/main.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<!-- Page Inner -->
<div class="page-inner no-page-title">
    <div id="main-wrapper">
        <div class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-style-1">
                    <li class="breadcrumb-item"><a href="#">Orders</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> / Order List</li>
                </ol>
            </nav>


            {% include 'snippets/messages.html' %}
            <div class="row">
                <div class="col-xl">
                    <div class="card">
                        <div class="card-body">
                            <div class="text text-center">
                                <h5 class="card-title">Orders</h5>
                            </div>

                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                data-target=".bd-example-modal-lg">Add New Order</button>
                            <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"
                                aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Add New Order</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            {% include 'orders/order_forms.html' with form=form %}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-dismiss="modal">Close</button>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>


                            <table class="table table-hover" id="table_id">
                                <thead>
                                    <tr>

                                        <th scope="col"> Item Name </th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">Department </th>
                                        <th scope="col">Order Date</th>
                                        <th scope="col">Action</th>

                                    </tr>
                                </thead>
                                <tbody>


                                </tbody>
                            </table>

                            <div id="roomform">
                                <button id="createRoom" class="btn"> Create Room </button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>





        </div>

    </div><!-- Main Wrapper -->


    {% endblock content %}

    {% block extrajs %}
    <script src="{% static './assets/js/app.js' %}">
    </script>
    {% endblock extrajs %}

templates/orders/mylist.html
<table class="table table-hover" id="table_id">
    <thead>
        <tr>

            <th scope="col"> Item Name </th>
            <th scope="col">Quantity</th>
            <th scope="col">Department </th>
            <th scope="col">Order Date</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>



        {% for order in orders  %}
        <tr>



            <td> <a href="{{order.get_absolute_url}}">{{order.shelf.item}}</a></td>
            <td>{{order.quantity}}</td>
            <td>{{order.department}}</td>
            <td>
                <a href="{{order.get_absolute_url}}">{{order.date_of_order}} |
                    ({{order.date_of_order|timesince}})</a>

            </td>
            <td><button type="button" class="btn btn-warning btn-sm js-update-book"
                    data-url="{% url 'orders:order_updates' order.id %}">
                    <span class="glyphicon glyphicon-pencil"></span> Edit
                </button>


                <button type="button" class="btn btn-danger btn-sm js-delete-book"
                    data-url="{% url 'orders:delete_order' order.id %}">
                    <span class="glyphicon glyphicon-trash"></span> Delete
                </button>

            </td>



        </tr>
        {% endfor %}

    </tbody>
</table>

templates/orders/new_order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<title>Items | New Order</title>




{% block content %}
<div class="page-inner no-page-title">
    <div id="main-wrapper">
        <div class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-style-1">
                    <li class="breadcrumb-item"><a href="{% url 'orders:list_order' %}">Orders</a></li>
                    <li class="breadcrumb-item active" aria-current="page">New Order</li>
                </ol>
            </nav>
            <h1 class="page-title">New Order</h1>
        </div>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12">












                                <div class="row">
                                    <div class="col-xl">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="text text-center">
                                                    <h5 class="card-title">PLACE ORDER</h5>
                                                </div>


                                                {% include 'orders/order_forms.html'  with form=form %}

                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- Main Wrapper -->

    {% endblock content %}

templates/orders/order_forms.html
{% load crispy_forms_tags %}
<form action="{% url 'orders:new_order' %}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy}}
    </div>





    <div class="form-group">
        <input type="submit" value="Add Item" class="btn btn-info">
    </div>

</form>

templates/orders/order_list.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<!-- Page Inner -->
<div class="page-inner no-page-title">
    <div id="main-wrapper">
        <div class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-style-1">
                    <li class="breadcrumb-item"><a href="{% url 'orders:list_order' %}">Orders</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Order List</li>
                </ol>
            </nav>


            {% include 'snippets/messages.html' %}
            <div class="row">
                <div class="col-xl">
                    <div class="card">
                        <div class="card-body">
                            <div class="text text-center">
                                <h5 class="card-title">Orders</h5>
                            </div>

                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                data-target=".bd-example-modal-lg">Add New Order</button>
                            <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"
                                aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Add New Order</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            {% include 'orders/order_forms.html' with form=form %}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-dismiss="modal">Close</button>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>


                            <table class="table table-hover" id="table_id">
                                <thead>
                                    <tr>

                                        <th scope="col"> Item Name </th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">Department </th>
                                        <th scope="col">Order Date</th>
                                        <th scope="col">Action</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders  %}
                                    <tr>



                                        <td> <a href="{{order.get_absolute_url}}">{{order.item}}</a></td>
                                        <td>{{order.quantity}}</td>
                                        <td>{{order.department}}</td>
                                        <td>
                                            <a href="{{order.get_absolute_url}}">{{order.date_of_order}} |
                                                ({{order.date_of_order|timesince}})</a>

                                        </td>
                                        <td><a href="{{order.get_absolute_url}}" class="btn btn-primary">View</a> </td>



                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>





        </div>

    </div><!-- Main Wrapper -->


    {% endblock content %}

    {% block extrajs %}
    <script src="{% static './assets/js/app.js' %}">
    </script>
    {% endblock extrajs %}