items/urls.py
from django.urls import path
from .views import (index, test_perm,
                    ItemUpdateView,
                    item_list,
                    item_detail_view,
                    expiring_list,
                    get_items,
                    delete_item,
                    search,
                    low_stock,
                    CategoryUpdateView,
                    CategoryCreateView,
                    delete_category,
                    category_detail,
                    cat_list,
                    item_page,
                    post_item,
                    add_to_shelf,
                    shelf_list, shelf_detail, update_shelf, delete_shelf, upload_excel


                    )

app_name = 'items'

urlpatterns = [

    path('add', test_perm, name='add'),
    path('add-item', item_page, name='add-item'),
    path('post-item', post_item, name="post-item"),
    path('upload-items', upload_excel, name="upload_items"),
    path("shelf/add-to-shelf", add_to_shelf, name="add_shelf"),
    path("shelf/list", shelf_list, name="shelf_list"),
    path("shelf/<int:pk>/detail", shelf_detail, name="shelf_detail"),
    path("shelf/<int:pk>/update", update_shelf, name="shelf_update"),
    path("shelf/<int:pk>/delete", delete_shelf, name="shelf_delete"),








    path('update/<int:pk>', ItemUpdateView.as_view(), name="item_update"),
    path('list', item_list, name='item_list'),
    path('expiring-list', expiring_list, name='expiring_list'),
    path('low-stock', low_stock, name='low_stock'),


    path("detail/<int:pk>/description", item_detail_view, name="item_detail"),
    path('<int:pk>/delete', delete_item, name='item_delete'),
    path("data", get_items, name="get-data"),
    path("search", search, name="search"),
    path("category/<int:pk>/update",
         CategoryUpdateView.as_view(), name="update_category"),
    path("category/create", CategoryCreateView.as_view(), name="category_create"),
    path("category/<int:pk>/delete", delete_category, name="category_delete"),
    path("category/list", cat_list, name="category_list"),
    path("category/<int:pk>/detail", category_detail, name="category_detail"),
    # path('item-update/<int:pk>', items_update, name="update"),



]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import ManagerSignUpView, user_list, UserCreateView, UserUpdateView, user_detail_view, user_update_view
from items.views import index, category_upload
from .views import ItemChart, chartview, settings_view, settings_update_view,upload_items
from carts.views import cart_home
from ajax_select import urls as ajax_select_urls

admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload-items',upload_items,name='upload-items'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/manager/',
         ManagerSignUpView.as_view(), name='manager_signup'),
    path('accounts/add/user/',
         UserCreateView.as_view(), name='add_user'),
    path('accounts/<int:pk>/update/user/',
         user_update_view, name='update_user'),
    path('accounts/<int:pk>/details/user/',
         user_detail_view, name='user_detail'),
    path('ajax_select/', include(ajax_select_urls)),



    path("accounts/users", user_list, name="users"),
    path("", index, name="index"),
    path("items/", include('items.urls')),
    path("orders/", include('orders.urls')),
    path("departments/", include("departments.urls")),
    path("api/chart/data/", ItemChart.as_view(), name="api-data"),
    path("chart/", chartview, name="chart"),
    path("cart", cart_home, name="cart"),
    path("upload", category_upload, name="upload"),
    path('settings', settings_view, name="settings"),
    # path('create-item', settings_view, name="create_item"),

    path('settings/<int:pk>/update', settings_update_view, name="settings_update"),







]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

items/forms.py
from django import forms
from .models import Category, User, Item, ItemSetting, ShelfItem


class DateInput(forms.DateInput):
    input_type = 'date'


class ItemForm(forms.ModelForm):

    class Meta:
        widgets = {'expiry_date': DateInput()}

        model = Item
        exclude = ('user', 'expired')


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ("name",)


class ItemSettingForm(forms.ModelForm):
    """ItemSttingForm definition."""

    # TODO: Define form fields here
    class Meta:
        model = ItemSetting
        fields = ("low_stock_limit", "item_expiration_limit")


class ShelfItemForm(forms.ModelForm):

    class Meta:
        model = ShelfItem
        fields = ("item", "quantity", "shelf")


class MoveToFormShelf(forms.ModelForm):

    class Meta:
        model = ShelfItem
        fields = ("quantity", "shelf")

items/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from .forms import ItemForm,CategoryForm,MoveToFormShelf,ShelfItemForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import UpdateView, DeleteView,CreateView
from .models import Item, User, Category,ItemSetting,ShelfItem
from datetime import datetime, timedelta
from django.http import JsonResponse
from .filters import ItemFilter
from orders.models import Order
from datetime import datetime
from django.db.models import Count
from django.db.models.functions import Trunc
from django.contrib.auth.decorators import user_passes_test
from tablib import Dataset
from .resources import CategoryResource
import openpyxl



@login_required
def index(request):
    current_month = datetime.now().month
    monthly_orders = Order.objects.filter(date_of_order__month=current_month)
    print(monthly_orders)

    month_order = Order.objects.annotate(order_month=Trunc(
        'date_of_order', 'month')).values('order_month').annotate(orders=Count('id'))
    for orders in month_order:
        print("whats {}".format(orders['orders']))
    items=Item.objects.all()
    date_me = datetime.now()+timedelta(60)
    expiring_product = Item.objects.filter(
        expiry_date__lte=date_me)
    expired = Item.objects.filter(expiry_date__lte=datetime.now())

    return render(request, "items/index.html", {'monthly_orders':monthly_orders,'expiring_product':expiring_product,'expired':expired,'items':items})


@login_required



def test_perm(request):
    form = ItemForm(request.POST or None, request.FILES or None)

    if request.method == "POST":
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, 'item has been added')

            return redirect('items:item_list')

    context = {
        'form': form
    }

    return render(request, 'items/add_items.html', context)


class ItemUpdateView(UpdateView,LoginRequiredMixin):
    model = Item
    form_class = ItemForm
    template_name = "items/update.html"
    

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()

        messages.success(self.request, "Item has been updated")
        return redirect('items:item_list')

@login_required
def item_list(request):
    form=ItemForm()
    items = Item.objects.all()
    date_me = datetime.now()+timedelta(60)
    today=datetime.now()

    expiring_product = Item.objects.filter(
        expiry_date__lte=date_me)
    expired = Item.objects.filter(expiry_date__lte=datetime.now())

    context = {
        'items': items,

        
        'expired': expired,
        'form':form,
        'today':today
        
    }
    print(date_me)
    print(expiring_product)
    print(datetime.now())

    return render(request, "items/item_list.html", context)

@login_required
def delete_item(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if request.method == "POST":
        item.delete()

        messages.success(request, 'Item has been deleted')
        return redirect('items:item_list')

    return redirect(request, 'snippets/delete_form.html')

@login_required
def item_detail_view(request, pk):

    item = get_object_or_404(Item, pk=pk)
    form = ItemForm(request.POST or None, request.FILES or None, instance=item)
    order_rel=item.order_set.all()
    print(" order _rel : {}".format(order_rel))


    context = {
        'item': item,
        'form': form
    }

    return render(request, 'items/item_detail.html', context)

@login_required
def expiring_list(request):
    sett = ItemSetting.objects.all()[0]
    # low_limit=sett.low_stock_limit
    exp_limit=sett.item_expiration_limit
    # print(exp_limit)
    # print(low_limit)
    items = Item.objects.all()
    date_me = datetime.now()+timedelta(exp_limit)
    expiring_product = Item.objects.filter(
        expiry_date__lte=date_me)
    expired = Item.objects.filter(expiry_date__lte=datetime.now())

    context = {
        'items': items,
        'expiring_products': expiring_product,
        'expired': expired
    }
    print(date_me)
    print(expiring_product)
    print(datetime.now())

    return render(request, "items/expiring_items.html", context)


def get_items(request, *args, **kwargs):
    data = {
        "sales": 50,
        "report": 70
    }

    return JsonResponse(data)

@login_required
def search(request):
    items = Item.objects.all()
    item_filter = ItemFilter(request.GET, queryset=items)

    context = {
        'filter': item_filter
    }

    return render(request, 'items/search.html', context)




def low_stock(request):
    sett = ItemSetting.objects.all()[0]
    low_limit=sett.low_stock_limit
    items=Item.objects.filter(stock_on_hand__lte=low_limit)


    return render(request,'items/low_stock.html',{'items':items})




class CategoryCreateView(CreateView):
    model = Category
    form_class=CategoryForm
    template_name = "category/category_form.html"

    def form_valid(self,form):


        form.save()
        messages.success(self.request,'Category has been added')
        return redirect('items:category_list')


class CategoryUpdateView(UpdateView):
    model = Category
    form_class=CategoryForm
    template_name = "category/category_update.html"

    def form_valid(self,form):
        form.save()
        messages.success(self.request,'Category has been updated')
        return redirect('items:update_category', pk=self.object.pk)

def delete_category(request,pk):
    cat=get_object_or_404(Category,pk=pk)

    if request.method=="POST":
        cat.delete()

        messages.success(request,'Category has been deleted')
        return reedirect('items:category_list')

        

def cat_list(request):
    cat=Category.objects.all()
    form=CategoryForm()

    context={
        'cats':cat,
        'form':form
    }

    return render(request,'category/category_list.html',context)




def category_detail(request,pk):
    cat=get_object_or_404(Category,pk=pk)
    form=CategoryForm()

    context={
        'cat':cat,
        'form':form

    }

    return render(request,'category/category_details.html',context)



# def simple_upload(request):
#     if request.method == 'POST':
#         storeitems_resource = StoreItemResource()
#         dataset = Dataset()
#         new_storeitems = request.FILES['myfile']

#         imported_data = dataset.load(new_storeitems.read())
#         result = storeitems_resource.import_data(dataset, dry_run=True)  # Test the data import

#         if not result.has_errors():
#             storeitems_resource.import_data(dataset, dry_run=False)  # Actually import now

#     return render(request, 'snippets/simple_upload.html')




def category_upload(request):
    if request.method == 'POST':
        category_resource = CategoryResource()
        dataset = Dataset()
        new_category = request.FILES['myfile']

        imported_data = dataset.load(new_category.read())
        result = category_resource.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            category_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'snippets/simple_upload.html')







def item_page(request):
    form=ItemForm()

    context={
        'form':form

    }

    return render(request,'items/add_items.html',context)
    




def post_item(request):
    if request.method=="POST" and request.is_ajax():
        form=ItemForm(request.POST or None , request.FILES or None)
        user=request.user
        print(user)

        
      
        form.instance.user=user
        form.save()

        return JsonResponse({'success':True},status=200)

        
    
    return JsonResponse({'success':False},status=400)


def get_category(value):
    qs=Category.objects.filter(name=value)
    if qs:
        return qs[0]
    else:
        
        qs=Category.objects.create(name=value)
        return qs[0]
    


def shelf_list(request):
    shelfs=ShelfItem.objects.all()
    context={
        'shelfs':shelfs

    }

    return render(request,'shelf/shelf_list.html',context)


def add_to_shelf(request):
    form=ShelfItemForm()

    if request.method=="POST":
        form=ShelfItemForm(request.POST or None)
        if form.is_valid():
            form.instance.user=request.user
            item=Item.objects.get(name=form.instance.item)

           
            
            if item.stock_on_hand < form.instance.quantity:
                
                messages.success(request,"Error! Maximum quantiy that can be moved to the shelf is {}".format(item.stock_on_hand))

                return redirect('/')
            elif item.stock_on_hand < 5:
                messages.success(request, 'Item is low on stock, only {} remaining'.format(item.stock_on_hand))
                return redirect('orders:list_order')
            else:
                print('good')
                shelf=shelf_items(form.instance.item)
                if shelf:
                    shelf.quantity=shelf.quantity + form.instance.quantity
                    shelf.shelf=form.instance.shelf
                    shelf.save()
                    item.stock_on_hand=item.stock_on_hand-form.instance.quantity
                    item.save()
                    messages.success(request,'I{} has been updated successfully'.format(form.instance.item))
                    return redirect('/')
                else:
                    item.stock_on_hand=item.stock_on_hand-form.instance.quantity
                    item.save()
                    form.save()
                    messages.success(request,'I{} has been added successfully'.format(form.instance.item))
                    return redirect('/')
                

templates/shelf/add_to_shelf.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<title>Items | Add To Shelf</title>




{% block content %}
<div class="page-inner no-page-title">
    <div id="main-wrapper">
        <div class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-style-1">
                    <li class="breadcrumb-item"><a href="#">Items</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Add Item To Shelf</li>
                </ol>
            </nav>
            <h1 class="page-title">New Order</h1>
        </div>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12">












                                <div class="row">
                                    <div class="col-xl">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="text text-center">
                                                    <h5 class="card-title">PLACE ORDER</h5>
                                                </div>


                                                {% include 'shelf/item_form.html'  with form=form %}

                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- Main Wrapper -->

    {% endblock content %}

templates/shelf/item_form.html
{% load crispy_forms_tags %}
<form action="{% url 'items:add_shelf' %}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}

        {{form|crispy}}
    </div>





    <div class="form-group">
        <input type="submit" value="Add Item" class="btn btn-info">
    </div>

</form>

templates/shelf/list.html
{% load static %}
{% for shelf in shelfs  %}
<tr>
    <td>
        <div class="profile-img">

            {% if shelf.item.image %}
            <img src="{{shelf.item.image.url}}" style="height:45px;width:45px;border-radius:50%;">
            {% else %}
            <img src="{% static './assets/images/no_image.jpg' %}" style="height:45px;width:45px;border-radius:50%;">
            {% endif %}


        </div>
    </td>


    <td href="{{item.get_absolute_url}}"> <a href="{{item.get_absolute_url}}">{{shelf.item.name}}</a></td>

    {% if shelf.item.stock_on_hand <= 10 %}

    <td> <span class="badge badge-danger">{{shelf.item.stock_on_hand}} LOW STOCK</span>
    </td>
    {% else %}
    <td>{{shelf.item.stock_on_hand}}</td>
    {% endif %}



    <td>{{shelf.item.expiry_date}}({{shelf.item.expiry_date|timeuntil}})</td>

    <td>{{shelf.shelf}}</td>


    <td>{{shelf.quantity}}</td>
    <td>{{shelf.date_add}}</td>

    <td>
        <a href="{{shelf.get_absolute_url}}" class="btn btn-primary">View</a>

        <button type="button" class="btn btn-primary js-update-item">
            <span class="glyphicon glyphicon-plus"></span>
            Edit
        </button>





</tr>

{% endfor %}

templates/shelf/shelf_detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Item | Detail
{% endblock title %}




{% block content %}
<div class="page-inner no-page-title">
    <div id="main-wrapper">
        <div class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-style-1">
                    <li class="breadcrumb-item"><a href="{% url 'items:item_list' %}">Items</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Item Detals</li>
                </ol>
            </nav>

        </div>


        <div class="row">
            <div class="col-xl">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md">
                                <div class="card">
                                    <div class="card-body">

                                        {% if item.image %}
                                        <img id="zoom_02" src="{{item.image.url}}" data-zoom-image="{{item.image.url}}"
                                            style="width: 100%;" alt="" />

                                        {% else %}
                                        <img id="zoom_02" src="{% static './assets/images/no_image.jpg' %}"
                                            data-zoom-image="{% static './assets/images/no_image.jpg' %}" {% endif %}"
                                            style="width: 100%;" alt="" />


                                    </div>
                                </div>
                            </div>


                            <div class="col-md">

                                <div class="card">
                                    <div class="card-body">
                                        <div class="text text-center">
                                            <h2 class="card-title">{{shelf.item.name|title}}</h2>
                                            <hr>

                                        </div>

                                        <h6> Stock On Hand: {{shelf.item.stock_on_hand}}</h6>
                                        <hr>
                                        <h6> Description: {{shelf.item.description|title}}</h6>
                                        <hr>
                                        <h6> Expiry Date:
                                            {{shelf.item.expiry_date|timeuntil}}({{shelf.item.expiry_date}})
                                        </h6>
                                        <hr>
                                        <h6> Date Added: {{shelf.item.timestamp|timesince}} Ago
                                            ({{shelf.item.timestamp}})
                                        </h6>
                                        <hr>
                                        <h6> Date Moved To Shelf: {{shelf.date_add|timesince}} Ago ({{shelf.date_add}})
                                        </h6>
                                        <hr>
                                        <h6> Shelf Number: {{shelf.item.shelf_number}}</h6>

                                        <hr>
                                        <h6> Added By: <a
                                                href="{{shelf.item.user.get_absolute_url}}">{{item.user|title}}</a>
                                        </h6>

                                        <hr>

                                        {% if user.is_superuser %}





                                        <button type="button" class="btn btn-primary" data-toggle="modal"
                                            data-target=".bd-example-modal-xl">Update</button>
                                        <div class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog"
                                            aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-xl">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalCenterTitle">
                                                            {{item.title|title}}
                                                        </h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">


                                                        {% include 'shelf/update_form.html' with form=form shelf=shelf %}
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary"
                                                            data-dismiss="modal">Close</button>
                                                        <button type="button" class="btn btn-primary">Save
                                                            changes</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>





                                        <button type="button" class="btn btn-danger" data-toggle="modal"
                                            data-target="#exampleModal">
                                            Delete
                                        </button>
                                        <!-- Modal -->
                                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel"> Remove
                                                            {{shelf.item.name}}</h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Are you sure you want to delete this item?

                                                        <form action="{% url 'items:shelf_delete' pk=shelf.pk %}"
                                                            method="post">
                                                            {% csrf_token %}
                                                            <input type="submit" value="Delete" class="btn btn-danger">
                                                        </form>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary"
                                                            data-dismiss="modal">Close</button>


                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        {% endif %}

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <div class="row">
            <div class="col-xl">
                <div class="card">
                    <div class="card-body">
                        <div class="text text-center">
                            <h5 class="card-title">RECENT ORDERS</h5>
                        </div>






                        <hr>
                        <table class="table table-hover" id="table_id">
                            <thead>
                                <tr>

                                    <th scope="col">Item Ordered </th>
                                    <th scope="col">Item Quantity</th>
                                    <th scope="col">Date Ordered</th>
                                    <th scope="col">Order ID</th>



                                </tr>
                            </thead>
                            <tbody>
                                {% for item in shelf.order_set.all  %}
                                <tr>



                                    <td><a href="{{item.get_absolute_url}}">{{item.shelf}}</a></td>
                                    <td><a href="{{item.get_absolute_url}}">{{item.quantity}}</a></td>
                                    <td><a href="{{item.get_absolute_url}}">{{item.date_of_order}}</a></td>
                                    <td><a href="http://"></a>{{item.order_id}}</td>





                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>








    </div>
</div><!-- Main Wrapper -->
{% endblock content %}

templates/shelf/update_form.html
{% load crispy_forms_tags %}
<form action="{{shelf.get_update_url}}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}

        {{form|crispy}}
    </div>





    <div class="form-group">
        <input type="submit" value="Add Item" class="btn btn-info">
    </div>

</form>

templates/shelf/upload_excel.html
<form action="{% url 'items:upload_items' %}" method="POST" enctype="multipart/form-data">
    <div class="custom-file">
        {% csrf_token %}
        <input type="file" class="custom-file-input form-control" name="excel_file" id="customFile">
        <label class="custom-file-label" for="customFile">Choose file</label>
    </div>

    <button type="submit" class="btn btn-info">Upload</button>

</form>